### ISSUE TITLE
Please publish latest version to rubygems

### ISSUE THREAD

**Issue by smnplk** [viclim/moment_timezone-rails#9]
There is currently only 0.2.1 on rubygems. I think some folks who have to maintain old rails apps will find the updated version useful. Thank you!

**Comment by chewi** [comment]
Yes please! I only noticed because of big deprecation warnings being spat out in the console.

**Comment by viclim** [comment]
Done. Please help me to test it.

**Comment by lsiebert** [comment]
Thanks for being responsive over email :-)

**Comment by chewi** [comment]
Working fine here, thanks!
